services:
  web-server:
    image: nginx:alpine
    container_name: nginx-nurz
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
